RegionId = 'cn-beijing'
AccessKeyId = ''
AccessKeySevcret = ''
StsOssEndPoint = 'sts.cn-beijing.aliyuncs.com'
OssEndPoint = 'http://oss-cn-beijing.aliyuncs.com'
Bucket = ''
TimeOut = 10800
RoleArn = '' # example 'acs:ram::111111111111:role/beijing-oss-uploader'
Role = ''
